/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFHEGovernance } from "./IFHEGovernance";
export type { IFHEQuadraticVoting } from "./IFHEQuadraticVoting";
export type { IFHEVoting } from "./IFHEVoting";
