/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ifheVotingSol from "./IFHEVoting.sol";
export type { ifheVotingSol };
export type { FHEBallot } from "./FHEBallot";
export type { FHEIdentityVault } from "./FHEIdentityVault";
export type { FHEQuadraticVoting } from "./FHEQuadraticVoting";
export type { FHEVotingBase } from "./FHEVotingBase";
